Add kafka codec, sink and source
shotover/shotover-proxy pull request #1042
Opened 2023-02-10 06:23 UTC by rukai

A trivial codec, sink and source implementation.
The codec and source seem fine, I think I just need to sort out some bugs in the sink.

DO NOT REVIEW YET: just publishing a draft so I remember what I was doing on monday

2023-02-13 01:30 UTC, conorbros requested changes
Can we put this behind alpha-transforms and add docs for it?

2023-02-13 01:37 UTC, rukai commented
I put it behind alpha-transforms an hour or so ago, maybe you were reviewing a slightly old version?

as for docs, the idea of alpha-transforms is that they dont have any docs yet, docs get added once they are moved into the public API.

2023-02-13 02:46 UTC, conorbros approved these changes

2023-02-15 22:57 UTC, benbromhead approved these changes
Good start! 

The one shot todo makes sense, and something to revisit when we start looking at perf

2023-02-16 00:01 UTC, merged