Instrument async code with tracing spans
shotover/shotover-proxy pull request #363
Opened 2021-11-09 03:38 UTC by rukai

Concurrent logs now look like this:
![image](https://user-images.githubusercontent.com/5120858/140857478-f563fa75-1ece-474c-b873-be26469e34ed.png)
This allows us to see through the noise and form a sequence of events from concurrent logs.

Possibly we should be using a random id instead of an incrementing value.

2021-11-09 04:31 UTC, rukai commented on shotover-proxy/src/transforms/chain.rs
> +        let _jh = tokio::spawn(
Very little was actually change here, the only thing I did here was call .in_current_span() but it made rust fmt freak out.

2021-11-09 14:57 UTC, conorbros requested changes
Everything looks good to me but we should add some tests before merging. 

Testing tracing: https://docs.rs/tracing-test/0.1.0/tracing_test/

2021-11-09 23:51 UTC, rukai commented
That library is way too inflexible to do anything with:
* No way to assert on spans (What this PR is actually changing)
* No way to assert on part of a log. e.g. we cant write an assertion for `New connection from 127.0.0.1:38602` because the port is random.
* No way to view the actual log after a failure.

The idea is cool but I think we'll have to revisit that later when its more than just a prototype.

2021-11-09 23:56 UTC, conorbros approved these changes
Fair enough. Would be nice to test but should be fine for the time being.

2021-11-10 04:17 UTC, XA21X approved these changes

2021-11-10 04:20 UTC, merged